baseURL: "https://ibanaressanchez.github.io" 
title: Ignacio Banares-Sanchez
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 2
params:
    description: "I am an Economics PhD Candidate at the London School of Economics. I work on questions in development and environmental economics. I am particularly intersted in clean energy, clean water, and sustainable cities. Currently, I am researching industrial, regional, and urban policies, around solar PV, solid waste, and sanitation. I use tools from applied microeconomics, urban economics, and economic geography."
    author: Ignacio Banares-Sanchez
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ignacio Banares-Sanchez
          subtitle: "I am an Economics PhD Candidate at the London School of Economics. I work on questions in development and environmental economics. I am particularly intersted in clean energy, clean water, and sustainable cities. Currently, I am researching industrial, regional, and urban policies, around solar PV, solid waste, and sanitation. I use tools for applied microeconomics, urban economics, and economic geography."
          imageUrl: 
          imageWidth: 160
          imageHeight: 160
          imageTitle: Ignacio Banares-Sanchez
          buttons:
            - name: Papers
              url: papers/
            - name: Teaching
              url: courses/
           
    socialIcons:
        - name: Email
          url: mailto:i.banares-sanchez@lse.ac.uk
        - name: CV
          url: cv.pdf
        - name: Office Hours
          url: officehours/

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: 
      icon: favicon.ico
      iconHeight: 15

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
